---
title: "Multiple Choice Questions"
author: "Tom De Natale"
date: "March 12, 2015"
output: html_document
---

## Lecture 1a

What are your impressions of day one for HS616 Statistical Computing for Biomedical Data?

* All of these answers
* I should have done the exercises and reading before class 1
* This looks like fun, so I need to get into it
* I should have bought the book earlier
* R we having fun yet?

## Lecture 1b

This is the correct way to set up a chunk of code to run in a RMarkdown file using RStudio?
```r
N<- 10000
```

* True
* False

## Lecture 2a

If you had 2 decks of cards, using the choose function in R, what code will attain the probability of selecting the same specific card from each deck?

* '1/(choose (52,1)* choose(52,1))'
* '1/(choose (52,2))'
* '1/(choose (52,1)* choose(51,2))'
* '1/(choose (2,52))'


## Lecture 2b 

Concepts that you need to master R in this class do NOT include:

* Fourier Transforms
*	All of these
*	Uniform Distribution(continuous)
*	Normal of Gaussian distribution (continuous)
*	Poisson distribution (discrete)
*	Binomial distribution (discrete)


## Lecture 3a

The diag function has multiple uses:
```
diag(x = 1, nrow, ncol)
diag(x) <- value
````

* Answers x,w,y, are true
* x) It can extract a diagonal given a matrix 
* w) It can construct a diagonal matrix 
* y) It can replace the diagonal of a matrix
* z) It can diagnose cancer without assistance.

## Lecture 3b

Given a Markov Matrix, which is true

* all entries of the matrix are nonnegative and the sum of each column vector
is equal to 1
* The sum of the rows is the square root of pi
* Markov Matrices can be NXM in size
* A Markov matrix is not a special classification of an Eigenvector 


## Lecture 4a

Choose the most appropriate answer for this R code calculating two ways the cost of daily medicine?
```
> price <- c( lisonopril=106/30, crestor=204.00/30, 
+             clorthiazide=12.10/15, fibrosol=160/30)
> dosage_day <- c( lisonopril=3, crestor=0.5, 
+             clorthiazide=0.5, fibrosol=1)
> 
> cost_day_1  = sum(price * dosage_day)
> cost_day_1a = price %*% dosage_day
> cost_day_1
[1] 19.73667
> cost_day_1a
         [,1]
[1,] 19.73667
> 
```

* The Dot product of 2 vectors equals the sum of the products of two vectors
* A vector times a vector is a scaler
* A diagonal times a vector of that diagonal results in a squared value
* R is fun only for statisticians


## Lecture 4b

Pastemyownhe following profiling results:
```
             self.time self.pct
"function_A"    278.39    86.46
"function_B"     29.32     9.10
"function_C"     14.29     4.44
```
If you make `function_B` 100 times faster, how much faster would you expect the program be?

* less than 10% faster
* twice as fast
* 100 times as fast
* no faster

## Lecture 5a

paste my own regular expressions below matches this sentence exactly once?
"The key, the whole key, and nothing but the key."

* "\\.$"
* "[Tt]he\\s"
* "(and|not)"
* "?key?"

## Lecture 5b

paste my ownse addresses cannot be read by the built-in `url()` function?

* `https://connect.usfca.edu`
* `http://rseek.org/`
* `http://ftp.ics.uci.edu/pub/machine-learning-databases/`
* `file:///usr/share/dict/words`

## Lecture 6a

sqldf is a fantastic tool for data scientists. Which of the following statements are true?

* All of these
* Right and full outer joins, which are unavailable in sqldf, can be accomplished with the "merge" function of base R
* sqldf is a useful tool for manipulation data with such statements such as:
sqldf::sqldf("SELECT * FROM A JOIN B ON a==b")
* sqldf operates on dataframes

## Lecture 6b

paste my ownnnection to an SQLite database?

* dsets <- dbConnect(RSQLite::SQLite(), "datasets.sqlite")
* res <- dbSendQuery(dsets, "select * from iris limit 10")
* sqliteCopyDatabase(dsets, "datasets.sqlite")
* dbListTables(dsets)

## Lecture 7a

Which is true of Tidy Data by Hadley Wickam?

* None of these other answers
* Data is always essentially tidy
* It is always possible to get to the ideal structure, that is attain a one to one relationship for all data
* It is bad for vectorization to have each observation in a row
* It is good to have the variables identified at the start of a row versus the variable as a column
* Wide tables with a unique entry for the first element each row are always better  than long tables which may have nonunique entries as the first element in multiple rows.

## Lecture 7b

What is TRUE of the following code and results? (Code was used in class as an example of how to build a model for our class project)?
```
> T_shirts <- data.frame(
+   sex=sample(c("M","F"), 100, replace=T), 
+   size=sample(c("L", "M", "S"), 100, replace=T)
+ )
> 
> table(T_shirts)
   size
sex  L  M  S
  F 19 19 17
  M 20 10 15
> xtabs(~ sex + size, T_shirts)
   size
sex  L  M  S
  F 19 19 17
  M 20 10 15
```

* Only sometimes result in the same data , as the code does not identify a seed.
* Always result in females having more small sizes
* Always result in males having more large sizes
* Always result in the same data
